## Agregação em um mesmo arquivo dos dados socioeconomicos adicionais coletados, para uso no treinamento do modelo.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_ideb = pd.read_csv("/content/br_historico_ideb_municipal.csv", delimiter=';')
df_gini = pd.read_csv("/content/br_indice_gini_uf.csv", delimiter=';')
df_pbf_2023 = pd.read_csv("/content/br_proporcao_pbf_2023.csv", delimiter=';')
df_pbf_2024 = pd.read_csv("/content/br_proporcao_pbf_2024.csv", delimiter=';')

In [ ]:
df_ideb = df_ideb.rename(columns={"nome_municipio": "municipio"})
df_ideb['municipio'] = df_ideb['municipio'].str.upper()

In [ ]:
df_gini_2023 = df_gini.filter(items=["Sigla", "2023"]).rename(columns={"Sigla": "sigla_uf", "2023": "gini"})
df_gini_2024 = df_gini.filter(items=["Sigla", "2024"]).rename(columns={"Sigla": "sigla_uf", "2024": "gini"})

In [ ]:
df_gini_2023['gini'] = df_gini_2023['gini'].replace(",", ".", regex=True).astype(np.float64)
df_gini_2024['gini'] = df_gini_2024['gini'].replace(",", ".", regex=True).astype(np.float64)

In [ ]:
df_pbf_2023 = df_pbf_2023.merge(df_gini_2023, on="sigla_uf", how="left").filter(items=["municipio", "sigla_uf", "proporcao", "gini"]).rename(columns={"proporcao": "proporcao_pbf_municipio", "gini": "gini_uf"})
df_pbf_2024 = df_pbf_2024.merge(df_gini_2024, on="sigla_uf", how="left").filter(items=["municipio", "sigla_uf", "proporcao", "gini"]).rename(columns={"proporcao": "proporcao_pbf_municipio", "gini": "gini_uf"})

In [ ]:
df_pbf_2023.head()

             municipio sigla_uf  proporcao_pbf_municipio  gini_uf
0  SERRANO DO MARANHÃO       MA                     1.00    0.491
1              ITAUBAL       AP                     1.00    0.491
2          SÃO ROBERTO       MA                     1.00    0.491
3               ANAJÁS       PA                     0.98    0.499
4        CAJAZEIRINHAS       PB                     0.98    0.561

In [ ]:
df_pbf_2024.head()

      municipio sigla_uf  proporcao_pbf_municipio  gini_uf
0    ACRELÂNDIA       AC                     0.47    0.502
1  ASSIS BRASIL       AC                     0.82    0.502
2     BRASILÉIA       AC                     0.49    0.502
3        BUJARI       AC                     0.47    0.502
4      CAPIXABA       AC                     0.54    0.502

In [ ]:
df_pbf_2023 = df_pbf_2023.merge(df_ideb, on=["municipio", "sigla_uf"], how="left")
df_pbf_2024 = df_pbf_2024.merge(df_ideb, on=["municipio", "sigla_uf"], how="left")

In [ ]:
df_pbf_2023["ano"] = 2023
df_pbf_2023 = df_pbf_2023.filter(items=["ano", "municipio", "sigla_uf", "proporcao_pbf_municipio", "ideb_medio", "tendencia_ideb","gini_uf"]).rename(columns={"ideb_medio": "ideb_medio_municipio", "tendencia_ideb": "tendencia_ideb_municipio"})

In [ ]:
df_pbf_2024["ano"] = 2024
df_pbf_2024 = df_pbf_2024.filter(items=["ano", "municipio", "sigla_uf", "proporcao_pbf_municipio", "ideb_medio", "tendencia_ideb","gini_uf"]).rename(columns={"ideb_medio": "ideb_medio_municipio", "tendencia_ideb": "tendencia_ideb_municipio"})

In [ ]:
df_pbf_2023.describe()

,ano,proporcao_pbf_municipio,ideb_medio_municipio,tendencia_ideb_municipio,gini_uf
count,5570.0,5570.000000,5570.000000,5570.000000,5570.000000
mean,2023.0,0.356896,5.644406,-0.016907,0.486728
std,0.0,0.209630,0.863617,0.615087,0.031089
min,2023.0,0.010000,3.170000,-2.300000,0.418000
25%,2023.0,0.180000,4.970000,-0.400000,0.472000
50%,2023.0,0.320000,5.770000,-0.030000,0.485000
75%,2023.0,0.540000,6.300000,0.330000,0.503000
max,2023.0,1.000000,8.730000,3.400000,0.561000

In [ ]:
df_pbf_2024.describe()

,ano,proporcao_pbf_municipio,ideb_medio_municipio,tendencia_ideb_municipio,gini_uf
count,5570.0,5570.000000,5570.000000,5570.000000,5570.000000
mean,2024.0,0.333296,5.644406,-0.016907,0.474787
std,0.0,0.192357,0.863617,0.615087,0.025132
min,2024.0,0.010000,3.170000,-2.300000,0.430000
25%,2024.0,0.170000,4.970000,-0.400000,0.454000
50%,2024.0,0.290000,5.770000,-0.030000,0.477000
75%,2024.0,0.500000,6.300000,0.330000,0.489000
max,2024.0,1.000000,8.730000,3.400000,0.547000

In [ ]:
df_socio_econ = pd.concat([df_pbf_2023, df_pbf_2024])

In [ ]:
df_socio_econ.sort_values(by=["ano", "sigla_uf", "municipio"]).head()

,ano,municipio,sigla_uf,proporcao_pbf_municipio,ideb_medio_municipio,tendencia_ideb_municipio,gini_uf
1575,2023,ACRELÂNDIA,AC,0.51,5.40,-0.20,0.51
37,2023,ASSIS BRASIL,AC,0.84,4.73,0.05,0.51
1494,2023,BRASILÉIA,AC,0.52,6.63,-0.63,0.51
1741,2023,BUJARI,AC,0.49,4.87,0.95,0.51
929,2023,CAPIXABA,AC,0.59,4.77,1.30,0.51

In [ ]:
df_socio_econ.describe()

,ano,proporcao_pbf_municipio,ideb_medio_municipio,tendencia_ideb_municipio,gini_uf
count,11140.000000,11140.000000,11140.000000,11140.000000,11140.000000
mean,2023.500000,0.345096,5.644406,-0.016907,0.480758
std,0.500022,0.201516,0.863578,0.615060,0.028890
min,2023.000000,0.010000,3.170000,-2.300000,0.418000
25%,2023.000000,0.170000,4.970000,-0.400000,0.461000
50%,2023.500000,0.310000,5.770000,-0.030000,0.477000
75%,2024.000000,0.520000,6.300000,0.330000,0.495000
max,2024.000000,1.000000,8.730000,3.400000,0.561000

In [ ]:
df_socio_econ.to_csv("br_dados_socioeconomicos.csv", index=False)