In [33]:
import sys
from pathlib import Path
import pandas as pd

sys.path.append(str(Path.cwd().parent))

from src.preprocessing import preprocessing

In [34]:
df = preprocessing.preprocess(False)

In [35]:
df.head()

,id_aluno,id_escola,nome_municipio,sigla_uf,feat_rede_encoded,feat_peso_aluno,feat_media_proficiencia_escola,feat_media_portugues_municipio,feat_media_portugues_estado,target_alfabetizado,target_nivel_alfabetizacao,ano,feat_total_participantes_escola,feat_percentual_faltantes_escola,feat_std_proficiencia_escola,feat_proporcao_pbf_municipio,feat_ideb_medio_municipio,feat_tendencia_ideb_municipio,feat_gini_uf
0,11008931,60000004,PORTO VELHO,RO,1,1.05,796.99,761.51,760.2,1,6,2023,114,7.02,34.88,0.29,5.4,0.07,454.0
1,11008904,60000004,PORTO VELHO,RO,1,1.00,796.99,761.51,760.2,1,8,2023,114,7.02,34.88,0.29,5.4,0.07,454.0
2,11008929,60000004,PORTO VELHO,RO,1,1.05,796.99,761.51,760.2,1,6,2023,114,7.02,34.88,0.29,5.4,0.07,454.0
3,11008935,60000004,PORTO VELHO,RO,1,1.05,796.99,761.51,760.2,1,6,2023,114,7.02,34.88,0.29,5.4,0.07,454.0
4,11008847,60000004,PORTO VELHO,RO,1,1.10,796.99,761.51,760.2,1,7,2023,114,7.02,34.88,0.29,5.4,0.07,454.0

TOTAL DE REGISTROS: 3354172 (Nenhum nulo após pre-processamento)

REGISTROS 2023: 1502542

REGISTROS 2024: 1851630

In [36]:
df.describe()

,id_aluno,id_escola,feat_rede_encoded,feat_peso_aluno,feat_media_proficiencia_escola,feat_media_portugues_municipio,feat_media_portugues_estado,target_alfabetizado,target_nivel_alfabetizacao,ano,feat_total_participantes_escola,feat_percentual_faltantes_escola,feat_std_proficiencia_escola,feat_proporcao_pbf_municipio,feat_ideb_medio_municipio,feat_tendencia_ideb_municipio,feat_gini_uf
count,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06,3.354172e+06
mean,3.209486e+07,6.002180e+07,1.111085e+00,1.148532e+00,7.483780e+02,7.480108e+02,7.477471e+02,5.915684e-01,4.428381e+00,2.023552e+03,7.695843e+01,1.182717e+01,4.038280e+01,2.882226e-01,5.684785e+00,-9.115644e-02,4.263845e+02
std,1.033286e+07,1.254817e+04,3.143056e-01,3.585416e-01,2.465181e+01,2.030736e+01,1.552018e+01,4.915438e-01,1.877040e+00,4.972848e-01,5.050947e+01,9.015035e+00,7.980302e+00,1.757630e-01,7.750341e-01,4.969347e-01,1.569276e+02
min,1.100000e+07,6.000000e+07,1.000000e+00,1.000000e-01,6.010600e+02,6.733000e+02,7.125600e+02,0.000000e+00,0.000000e+00,2.023000e+03,3.000000e+00,0.000000e+00,0.000000e+00,1.000000e-02,3.170000e+00,-2.300000e+00,4.300000e-01
25%,2.502554e+07,6.001124e+07,1.000000e+00,1.000000e+00,7.328700e+02,7.358000e+02,7.373000e+02,0.000000e+00,3.000000e+00,2.023000e+03,4.100000e+01,5.330000e+00,3.539000e+01,1.500000e-01,5.130000e+00,-4.000000e-01,4.580000e+02
50%,3.118988e+07,6.002210e+07,1.000000e+00,1.090000e+00,7.469500e+02,7.461800e+02,7.472800e+02,1.000000e+00,5.000000e+00,2.024000e+03,6.600000e+01,1.028000e+01,4.065000e+01,2.400000e-01,5.810000e+00,-1.000000e-01,4.770000e+02
75%,4.104087e+07,6.003279e+07,1.000000e+00,1.210000e+00,7.614900e+02,7.568300e+02,7.546800e+02,1.000000e+00,6.000000e+00,2.024000e+03,1.010000e+02,1.667000e+01,4.560000e+01,4.000000e-01,6.300000e+00,2.000000e-01,4.890000e+02
max,5.302770e+07,6.004281e+07,4.000000e+00,1.425500e+02,8.850200e+02,8.684600e+02,7.973400e+02,1.000000e+00,8.000000e+00,2.024000e+03,4.410000e+02,9.895000e+01,1.179100e+02,1.000000e+00,8.730000e+00,3.400000e+00,5.610000e+02

In [37]:
df.groupby('ano').count()

,id_aluno,id_escola,nome_municipio,sigla_uf,feat_rede_encoded,feat_peso_aluno,feat_media_proficiencia_escola,feat_media_portugues_municipio,feat_media_portugues_estado,target_alfabetizado,target_nivel_alfabetizacao,feat_total_participantes_escola,feat_percentual_faltantes_escola,feat_std_proficiencia_escola,feat_proporcao_pbf_municipio,feat_ideb_medio_municipio,feat_tendencia_ideb_municipio,feat_gini_uf
ano,,,,,,,,,,,,,,,,,,
2023,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542,1502542
2024,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630,1851630